[workspace]
authors = [
    "Klaus Zimmermann <zklaus@gmail.com>",
    "Jaime Rodríguez-Guerra <jaime.rogue@gmail.com>",
]
channels = ["conda-forge"]
name = "cf"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
rust = ">=1.90.0,<1.91"
